# File name: test.kv

<SmallButton@Button>:
    size_hint: None, None
    size: 100, 50

<GridLayout>:  
    rows: 4  
    cols_minimum: {0: 200, 1: 300, 2: 150}    
    rows_minimum: {0: 100, 1: 70, 2: 200, 3: 100}
        
    SmallButton:
        text: 'Button 1'            
    SmallButton:
        text: 'Button 2' 
    SmallButton:
        text: 'Button 3' 
    SmallButton:
        text: 'Button 4' 
    SmallButton:
        text: 'Button 5'         
    SmallButton:
        text: 'Button 6'             
    SmallButton:
        text: 'Button 7' 
    SmallButton:
        text: 'Button 8' 
    SmallButton:
        text: 'Button 9' 
    SmallButton:
        text: 'Button 10' 
