# File name: test.kv

<MyCustomButton>:
    text: str(self.size)
    size: 120, 40
    color: .7, .6, .4, 1

<MyCustomSlider>:    
    min: 0
    max: 100
    value: 25

<MyCustomVerticalSlider@MyCustomSlider>:    
    orientation: 'vertical'
    height: 180
    on_value: app.addTrack(self, 5) if self.value > 50 else app.removeTrack(self)

<MyCustomWidget>: 
    TextInput:
        hint_text: 'Type something'
        pos: root.x + 20, root.top - self.height - 20
        size: 300, 40   
        text: str(root.size)

    MyCustomButton:
        pos: root.x + 20, root.y + 20
        
    MyCustomButton:
        text: app.message
        pos: root.right - self.width - 20, root.y + 20
        on_press: app.changeText(self)

    MyCustomSlider:
        pos: root.x + 20, root.y + 60
        width: 300
        value: app.slider_value

    MyCustomVerticalSlider:
        pos: root.right - 400, root.top - 240

    MyCustomVerticalSlider:
        pos: root.right - 300, root.top - 240
        max: 200

