#:kivy 1.11.1
# File name: test.kv

<TestLayout>:
    canvas:        
        Color:
            rgba: 0, 1, 0, 1       
        Line:
            points: 100, 100, 120, 200, 150, 120, 180, 150, 200, 100
            close: True
            width: 5  

        PushMatrix

        Scale:
            xyz: 2, 2, 0 
            origin: 100, 100

        Translate:
            x: 200

        Line:
            points: 100, 100, 120, 200, 150, 120, 180, 150, 200, 100
            close: True 
            width: 5  

        PopMatrix    

    Label:
        text: 'Done'
        font_size: 40
        pos: 100, 200
        size_hint: None, None
        size: 100, 50
